"""
long_term_memory.py

Persistent cross-session memory store backed by Neo4j, with an integrated
knowledge graph (GraphRAG) for capturing relationships between facts.

Replaces the standalone memory MCP server (mcp/memory/) by running the same
persistence logic in-process alongside the FastAPI backend.  Embedding is
handled by the shared embeddings.py module (sentence-transformers +
ThreadPoolExecutor), so there is exactly one model instance and one thread-pool
in the process.

Neo4j's native graph model stores entities and relationships as first-class
graph primitives, and its built-in vector indexes (since 5.11) provide cosine-
similarity ranking for embedding-based semantic search.

Architecture
------------
The store has two layers:

1. **Flat memory store** (``Memory`` nodes): raw text blobs with cosine
   similarity ranking via a Neo4j vector index.  Used for raw evidence
   persistence and simple semantic search.

2. **Knowledge graph** (``KnowledgeGraph``): Entity and Community nodes with
   a rich set of relationship types supporting structural recall, provenance
   tracking, contradiction detection, and hierarchical taxonomy.

Relationship Types
------------------
  RELATES_TO   — directed factual relationship between entities (primary)
  IS_A         — hierarchical taxonomy (child → parent category)
  CONTRADICTS  — flags two entities as involved in conflicting claims
  SOURCED_FROM — entity or memory → source URL node
  MEMBER_OF    — entity → community cluster

Node Types
----------
  Memory    — raw evidence text blobs
  Entity    — named concepts extracted from research findings
  Community — LLM-summarized entity clusters
  Source    — web sources (URL + title + credibility score)

Public API
----------
  async_init()                               → None  (call once after event loop starts)
  store(content, category, importance, tags) → Dict
  find_similar(query, limit, min_similarity) → List[Dict]
  recall(query, category, min_importance,    → List[Dict]
         limit, similarity_threshold)

Graph API (via .graph attribute)
---------------------------------
  graph.upsert_entity(name, entity_type, description, session_id)         → Dict
  graph.store_relationship(source, target, relation, evidence, ...)        → Dict
  graph.store_hierarchy(child_name, parent_name)                           → Dict
  graph.store_contradiction(rel_id_a, rel_id_b, explanation, session_id)  → Dict
  graph.store_source(url, title, credibility_score)                        → Dict
  graph.link_to_source(entity_name, source_url)                            → Dict
  graph.find_entities(query, limit, include_hierarchy)                     → List[Dict]
  graph.find_contradictions(entity_names, limit)                           → List[Dict]
  graph.get_relationships(entity_ids, max_hops)                            → List[Dict]
  graph.get_communities(entity_ids)                                        → List[Dict]
  graph.get_provenance(entity_names)                                       → List[Dict]
  graph.recent_entities(since_date, limit)                                 → List[Dict]
  graph.recent_relationships(since_date, limit)                            → List[Dict]
  graph.session_diff(session_id)                                           → Dict
  graph.find_paths(source_name, target_name, max_depth)                    → List[Dict]
  graph.find_common_neighbors(entity_names, min_shared)                    → List[Dict]
  graph.decay_confidence(half_life_days)                                   → int
  graph.prune(min_confidence, max_age_days, dry_run)                       → Dict
  graph.update_communities(summarize_fn)                                   → int
  graph.recall_graph_context(query, entity_limit, max_hops, ...)          → str
  graph.stats()                                                             → Dict
"""

from __future__ import annotations

import json
import logging
import uuid
from collections import defaultdict
from datetime import datetime
from typing import Any, Callable, Coroutine, Dict, List, Optional

import neo4j
from neo4j import AsyncGraphDatabase

logger = logging.getLogger(__name__)

# Cosine similarity threshold above which a candidate is considered a
# near-duplicate of an already-stored memory.
_DEDUP_THRESHOLD: float = 0.95

# Cosine similarity threshold for entity deduplication — entities with names
# that embed above this are considered the same entity and merged.
_ENTITY_DEDUP_THRESHOLD: float = 0.92

# Minimum number of shared relationships for two entities to be grouped
# into the same community during community detection.
_COMMUNITY_MIN_SHARED_RELS: int = 2


class AsyncLongTermMemory:
    """
    Async, in-process persistent memory store backed by Neo4j.

    Embeddings are generated by the shared ``embeddings.py`` module and stored
    as properties on Neo4j nodes.  Vector indexes provide cosine-similarity
    search over those embeddings.

    Usage
    -----
    ltm = AsyncLongTermMemory(neo4j_uri="bolt://localhost:7687")
    await ltm.async_init()   # call once, after the event loop is running

    await ltm.store("Key finding: X is true", category="research_finding", importance=7)
    memories = await ltm.find_similar("what do we know about X?", limit=5)
    """

    def __init__(
        self,
        neo4j_uri: str = "bolt://localhost:7687",
        neo4j_user: str = "neo4j",
        neo4j_password: str = "research_pass",
        neo4j_database: str = "neo4j",
        embedding_dimensions: int = 384,
    ) -> None:
        self._uri = neo4j_uri
        self._user = neo4j_user
        self._password = neo4j_password
        self._database = neo4j_database
        self._embedding_dimensions = embedding_dimensions
        self._driver: Optional[neo4j.AsyncDriver] = None
        # Set to False if async_init() fails (Neo4j unavailable); all
        # public methods become no-ops so the research pipeline is unaffected.
        self._available: bool = False
        # Knowledge graph layer — shares the same Neo4j driver.
        self.graph: KnowledgeGraph = KnowledgeGraph(self)

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    async def async_init(self) -> None:
        """Initialize the Neo4j driver, constraints, and vector indexes.

        Must be called once after the asyncio event loop is running (e.g. from
        the FastAPI lifespan handler).  Idempotent — safe to call multiple times.

        Failures are logged as warnings rather than raised so that an unavailable
        Neo4j instance never blocks server startup.  When init fails, all public
        methods silently return empty results.
        """
        try:
            self._driver = AsyncGraphDatabase.driver(
                self._uri, auth=(self._user, self._password)
            )
            await self._driver.verify_connectivity()
            await self._create_schema()
            self._available = True
            logger.info(
                "[LongTermMemory] Ready — uri=%s  database=%s",
                self._uri,
                self._database,
            )
        except Exception as exc:
            logger.warning(
                "[LongTermMemory] Initialization failed — long-term memory will be "
                "disabled for this session.  Cause: %s",
                exc,
            )

    async def _create_schema(self) -> None:
        """Create uniqueness constraints and vector indexes (idempotent)."""
        assert self._driver is not None
        dims = self._embedding_dimensions
        async with self._driver.session(database=self._database) as session:
            # Uniqueness constraints
            await session.run(
                "CREATE CONSTRAINT memory_id IF NOT EXISTS "
                "FOR (m:Memory) REQUIRE m.id IS UNIQUE"
            )
            await session.run(
                "CREATE CONSTRAINT entity_id IF NOT EXISTS "
                "FOR (e:Entity) REQUIRE e.id IS UNIQUE"
            )
            await session.run(
                "CREATE CONSTRAINT community_id IF NOT EXISTS "
                "FOR (c:Community) REQUIRE c.id IS UNIQUE"
            )
            # Vector indexes for cosine similarity search
            await session.run(
                "CREATE VECTOR INDEX memory_embedding_idx IF NOT EXISTS "
                "FOR (m:Memory) ON (m.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )
            await session.run(
                "CREATE VECTOR INDEX entity_embedding_idx IF NOT EXISTS "
                "FOR (e:Entity) ON (e.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )
            await session.run(
                "CREATE VECTOR INDEX community_embedding_idx IF NOT EXISTS "
                "FOR (c:Community) ON (c.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )
            # Source provenance node constraint
            await session.run(
                "CREATE CONSTRAINT source_url IF NOT EXISTS "
                "FOR (s:Source) REQUIRE s.url IS UNIQUE"
            )

    async def close(self) -> None:
        """Close the Neo4j driver.  Call during application shutdown."""
        if self._driver is not None:
            await self._driver.close()
            self._driver = None
            self._available = False

    # ------------------------------------------------------------------
    # Public async API
    # ------------------------------------------------------------------

    async def store(
        self,
        content: str,
        category: str = "general",
        importance: int = 5,
        tags: Optional[List[str]] = None,
        extra_metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Store a memory.  Returns ``{"success": False}`` if LTM is unavailable."""
        if not self._available:
            return {"success": False, "message": "LongTermMemory not available"}

        if not content or not content.strip():
            return {"success": False, "message": "Empty content"}

        from embeddings import embed_texts, EmbeddingError, EMBEDDINGS_ENABLED

        vector: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                vecs = await embed_texts([content])
                vector = vecs[0] if vecs else None
            except EmbeddingError as exc:
                logger.debug(
                    "[LongTermMemory] Embedding unavailable for store: %s", exc
                )
            except Exception as exc:
                logger.debug(
                    "[LongTermMemory] Unexpected embed error in store: %s", exc
                )

        assert self._driver is not None
        memory_id = str(uuid.uuid4())
        now = datetime.now().isoformat()
        tags_list = tags or []
        extra = extra_metadata or {}

        async with self._driver.session(database=self._database) as session:
            try:
                # Dedup check via vector similarity
                if vector is not None:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'memory_embedding_idx', 1, $vector"
                        ") YIELD node, score "
                        "WHERE score >= $threshold "
                        "RETURN node.id AS id, score",
                        vector=vector,
                        threshold=_DEDUP_THRESHOLD,
                    )
                    record = await result.single()
                    if record:
                        return {
                            "success": False,
                            "memory_id": record["id"],
                            "message": (
                                f"Near-duplicate already stored "
                                f"(similarity={record['score']:.3f})"
                            ),
                        }

                # Build the CREATE query
                props: Dict[str, Any] = {
                    "id": memory_id,
                    "content": content,
                    "category": category,
                    "importance": importance,
                    "created_at": now,
                    "last_accessed": now,
                    "access_count": 0,
                    "tags": json.dumps(tags_list),
                }
                for k, v in extra.items():
                    props[f"custom_{k}"] = (
                        json.dumps(v) if isinstance(v, (list, dict)) else v
                    )
                if vector is not None:
                    props["embedding"] = vector

                await session.run(
                    "CREATE (m:Memory) SET m = $props",
                    props=props,
                )
                return {"success": True, "memory_id": memory_id, "message": "Stored"}

            except Exception as exc:
                logger.error("[LongTermMemory] store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    async def find_similar(
        self,
        query: str,
        limit: int = 5,
        min_similarity: float = 0.7,
    ) -> List[Dict[str, Any]]:
        """Find memories semantically similar to *query*. Returns [] if LTM unavailable."""
        if not self._available:
            return []
        return await self.recall(
            query=query,
            limit=limit,
            similarity_threshold=min_similarity,
        )

    async def recall(
        self,
        query: Optional[str] = None,
        category: Optional[str] = None,
        min_importance: Optional[int] = None,
        limit: int = 10,
        similarity_threshold: float = 0.0,
    ) -> List[Dict[str, Any]]:
        """Recall memories via semantic search.  Returns [] if LTM unavailable."""
        if not self._available:
            return []

        if not query:
            return await self._recall_no_query(category, min_importance, limit)

        from embeddings import (
            embed_query as _embed_q,
            EmbeddingError,
            EMBEDDINGS_ENABLED,
        )

        query_vec: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                query_vec = await _embed_q(query)
            except EmbeddingError as exc:
                logger.debug(
                    "[LongTermMemory] Embedding unavailable for recall: %s", exc
                )
            except Exception as exc:
                logger.debug(
                    "[LongTermMemory] Unexpected embed error in recall: %s", exc
                )

        if query_vec is None:
            return await self._recall_no_query(category, min_importance, limit)

        return await self._recall_with_vector(
            query_vec, category, min_importance, limit, similarity_threshold
        )

    # ------------------------------------------------------------------
    # Internal recall helpers
    # ------------------------------------------------------------------

    async def _recall_with_vector(
        self,
        query_vec: List[float],
        category: Optional[str],
        min_importance: Optional[int],
        limit: int,
        similarity_threshold: float,
    ) -> List[Dict[str, Any]]:
        assert self._driver is not None
        # Fetch more than needed to allow post-filtering
        fetch_limit = limit * 2

        where_parts: List[str] = []
        params: Dict[str, Any] = {
            "vector": query_vec,
            "fetch_limit": fetch_limit,
            "threshold": similarity_threshold,
        }
        if category:
            where_parts.append("node.category = $category")
            params["category"] = category
        if min_importance is not None:
            where_parts.append("node.importance >= $min_importance")
            params["min_importance"] = min_importance

        where_clause = ""
        if where_parts:
            where_clause = " AND " + " AND ".join(where_parts)

        cypher = (
            "CALL db.index.vector.queryNodes("
            "  'memory_embedding_idx', $fetch_limit, $vector"
            ") YIELD node, score "
            f"WHERE score >= $threshold{where_clause} "
            "RETURN node, score "
            "ORDER BY node.importance * score DESC "
            "LIMIT $limit"
        )
        params["limit"] = limit

        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(cypher, **params)
                records = await result.data()
            except Exception as exc:
                logger.debug("[LongTermMemory] recall query failed: %s", exc)
                return []

        now = datetime.now().isoformat()
        memories: List[Dict[str, Any]] = []
        update_ids: List[str] = []

        for rec in records:
            node = rec["node"]
            score = rec["score"]
            memories.append(self._unpack(node, score))
            update_ids.append(node["id"])

        # Batch-update access stats (best-effort)
        if update_ids:
            try:
                async with self._driver.session(database=self._database) as session:
                    await session.run(
                        "UNWIND $ids AS mid "
                        "MATCH (m:Memory {id: mid}) "
                        "SET m.last_accessed = $now, "
                        "    m.access_count = m.access_count + 1",
                        ids=update_ids,
                        now=now,
                    )
            except Exception:
                pass

        return memories

    async def _recall_no_query(
        self,
        category: Optional[str],
        min_importance: Optional[int],
        limit: int,
    ) -> List[Dict[str, Any]]:
        assert self._driver is not None

        where_parts: List[str] = []
        params: Dict[str, Any] = {"limit": limit}
        if category:
            where_parts.append("m.category = $category")
            params["category"] = category
        if min_importance is not None:
            where_parts.append("m.importance >= $min_importance")
            params["min_importance"] = min_importance

        where_clause = " WHERE " + " AND ".join(where_parts) if where_parts else ""
        cypher = f"MATCH (m:Memory){where_clause} RETURN m LIMIT $limit"

        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(cypher, **params)
                records = await result.data()
            except Exception as exc:
                logger.debug("[LongTermMemory] recall (no query) failed: %s", exc)
                return []

        return [self._unpack(rec["m"], 0.0) for rec in records]

    @staticmethod
    def _unpack(node: Dict[str, Any], score: float) -> Dict[str, Any]:
        tags = json.loads(node.get("tags", "[]"))
        custom: Dict[str, Any] = {}
        for k, v in node.items():
            if k.startswith("custom_"):
                try:
                    custom[k[7:]] = json.loads(v)
                except Exception:
                    custom[k[7:]] = v
        return {
            "id": node.get("id"),
            "content": node.get("content"),
            "category": node.get("category"),
            "importance": node.get("importance"),
            "created_at": node.get("created_at"),
            "last_accessed": node.get("last_accessed"),
            "access_count": node.get("access_count", 0),
            "tags": tags,
            "metadata": custom or None,
            "similarity": round(score, 4),
        }


# ---------------------------------------------------------------------------
# Knowledge Graph (GraphRAG)
# ---------------------------------------------------------------------------


class KnowledgeGraph:
    """
    Relationship-aware knowledge graph stored natively in Neo4j.

    Three node types:

    * **Entity**: Named concepts, people, technologies, organizations.
      Embedded by ``name + ": " + description`` so semantic search finds
      entities by meaning, not just exact name match.

    * **RELATES_TO relationships**: Directed edges ``source → relation → target``
      with evidence text.  Stored as native Neo4j relationships for efficient
      multi-hop traversal.

    * **Community**: LLM-generated summaries of densely-connected entity
      clusters, linked via ``MEMBER_OF`` edges.  Updated as a post-synthesis
      background task.

    All public methods are async.  The ``_ltm`` back-reference provides access
    to the ``_available`` flag and the Neo4j driver.
    """

    def __init__(self, ltm: AsyncLongTermMemory) -> None:
        self._ltm = ltm

    @property
    def _driver(self) -> Optional[neo4j.AsyncDriver]:
        return self._ltm._driver

    @property
    def _database(self) -> str:
        return self._ltm._database

    @property
    def available(self) -> bool:
        return self._ltm._available and self._driver is not None

    # ------------------------------------------------------------------
    # Entity CRUD
    # ------------------------------------------------------------------

    async def upsert_entity(
        self,
        name: str,
        entity_type: str = "concept",
        description: str = "",
        session_id: str = "",
    ) -> Dict[str, Any]:
        """Insert or update an entity.  Deduplicates by semantic name similarity."""
        if not self.available or not name or not name.strip():
            return {"success": False, "message": "Graph not available or empty name"}

        from embeddings import embed_texts, EmbeddingError, EMBEDDINGS_ENABLED

        doc_text = f"{name}: {description}" if description else name
        vector: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                vecs = await embed_texts([doc_text])
                vector = vecs[0] if vecs else None
            except (EmbeddingError, Exception) as exc:
                logger.debug("[KnowledgeGraph] Embedding failed for entity: %s", exc)

        assert self._driver is not None
        now = datetime.now().isoformat()
        name_stripped = name.strip()
        desc_stripped = description.strip()

        async with self._driver.session(database=self._database) as session:
            # Dedup: check if a semantically similar entity already exists
            if vector is not None:
                try:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'entity_embedding_idx', 1, $vector"
                        ") YIELD node, score "
                        "WHERE score >= $threshold "
                        "RETURN node, score",
                        vector=vector,
                        threshold=_ENTITY_DEDUP_THRESHOLD,
                    )
                    record = await result.single()
                    if record:
                        existing = record["node"]
                        existing_id = existing["id"]
                        mention_count = existing.get("mention_count", 1) + 1
                        sessions = json.loads(existing.get("source_sessions", "[]"))
                        if session_id and session_id not in sessions:
                            sessions.append(session_id)
                        existing_desc = existing.get("description", "")
                        new_doc = (
                            f"{name_stripped}: {desc_stripped}"
                            if desc_stripped
                            else name_stripped
                        )
                        use_doc = (
                            new_doc
                            if len(new_doc) > len(existing_desc)
                            else existing_desc
                        )
                        update_props: Dict[str, Any] = {
                            "mention_count": mention_count,
                            "source_sessions": json.dumps(sessions),
                            "last_seen": now,
                            "description": use_doc,
                            "last_confirmed": now,
                            "confirmation_count": existing.get("confirmation_count", 1)
                            + 1,
                        }
                        if vector is not None:
                            update_props["embedding"] = vector

                        await session.run(
                            "MATCH (e:Entity {id: $eid}) " "SET e += $props",
                            eid=existing_id,
                            props=update_props,
                        )
                        return {
                            "success": True,
                            "entity_id": existing_id,
                            "merged": True,
                            "mention_count": mention_count,
                        }
                except Exception as exc:
                    logger.debug("[KnowledgeGraph] Entity dedup check failed: %s", exc)

            # New entity
            entity_id = str(uuid.uuid4())
            props: Dict[str, Any] = {
                "id": entity_id,
                "name": name_stripped,
                "entity_type": entity_type,
                "description": (
                    f"{name_stripped}: {desc_stripped}"
                    if desc_stripped
                    else name_stripped
                ),
                "mention_count": 1,
                "first_seen": now,
                "last_seen": now,
                "last_confirmed": now,
                "confirmation_count": 1,
                "source_sessions": json.dumps([session_id] if session_id else []),
            }
            if vector is not None:
                props["embedding"] = vector

            try:
                await session.run(
                    "CREATE (e:Entity) SET e = $props",
                    props=props,
                )
                return {"success": True, "entity_id": entity_id, "merged": False}
            except Exception as exc:
                logger.error("[KnowledgeGraph] Entity store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    # ------------------------------------------------------------------
    # Relationship CRUD
    # ------------------------------------------------------------------

    async def store_relationship(
        self,
        source: str,
        target: str,
        relation: str,
        evidence: str = "",
        confidence: float = 0.8,
        session_id: str = "",
        step_id: int = 0,
    ) -> Dict[str, Any]:
        """Store a directed relationship between two entities.

        Deduplicates by (source, target, relation_type): if an identical triple
        already exists, the existing edge is updated rather than duplicated —
        confidence is raised to the higher of the two values, evidence is
        appended (if new), and confirmation_count is incremented.
        """
        if not self.available:
            return {"success": False, "message": "Graph not available"}
        if not source.strip() or not target.strip() or not relation.strip():
            return {
                "success": False,
                "message": "Source, target, and relation required",
            }

        assert self._driver is not None
        now = datetime.now().isoformat()
        src = source.strip()
        tgt = target.strip()
        rel = relation.strip()
        evid = evidence.strip()

        async with self._driver.session(database=self._database) as session:
            try:
                # ── Dedup check: exact match on source→target + relation_type ─
                result = await session.run(
                    "MATCH (s:Entity {name: $source})-[r:RELATES_TO]->(t:Entity {name: $target}) "
                    "WHERE r.relation_type = $relation "
                    "RETURN r.id AS rid, r.confidence AS conf, "
                    "       r.evidence AS evid, r.confirmation_count AS cnt",
                    source=src,
                    target=tgt,
                    relation=rel,
                )
                existing = await result.single()
                if existing:
                    # Merge into existing edge
                    existing_evid = existing["evid"] or ""
                    merged_evid = (
                        f"{existing_evid}; {evid}".strip("; ")
                        if evid and evid not in existing_evid
                        else existing_evid
                    )
                    new_conf = max(existing["conf"] or 0.8, confidence)
                    new_count = (existing["cnt"] or 1) + 1
                    await session.run(
                        "MATCH ()-[r:RELATES_TO {id: $rid}]->() "
                        "SET r.confidence = $conf, "
                        "    r.confirmation_count = $cnt, "
                        "    r.evidence = $evid, "
                        "    r.last_confirmed = $now",
                        rid=existing["rid"],
                        conf=new_conf,
                        cnt=new_count,
                        evid=merged_evid,
                        now=now,
                    )
                    return {
                        "success": True,
                        "relationship_id": existing["rid"],
                        "merged": True,
                    }

                # ── Create new edge ──────────────────────────────────────────
                rel_id = str(uuid.uuid4())
                await session.run(
                    "MATCH (s:Entity {name: $source}) "
                    "MATCH (t:Entity {name: $target}) "
                    "CREATE (s)-[:RELATES_TO {"
                    "  id: $rel_id, relation_type: $relation, "
                    "  confidence: $confidence, evidence: $evidence, "
                    "  session_id: $session_id, step_id: $step_id, "
                    "  created_at: $now, last_confirmed: $now, "
                    "  confirmation_count: 1"
                    "}]->(t)",
                    source=src,
                    target=tgt,
                    rel_id=rel_id,
                    relation=rel,
                    confidence=confidence,
                    evidence=evid,
                    session_id=session_id,
                    step_id=step_id,
                    now=now,
                )
                return {"success": True, "relationship_id": rel_id, "merged": False}
            except Exception as exc:
                logger.error("[KnowledgeGraph] Relationship store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    # ------------------------------------------------------------------
    # Entity search
    # ------------------------------------------------------------------

    async def find_entities(
        self,
        query: str,
        limit: int = 5,
        include_hierarchy: bool = False,
    ) -> List[Dict[str, Any]]:
        """Find entities semantically similar to *query*.

        If *include_hierarchy* is True, each result also carries an
        ``ancestors`` list of parent entity names (via IS_A edges, up to
        3 hops) so the caller can surface broader category context.
        """
        if not self.available:
            return []

        from embeddings import (
            embed_query as _embed_q,
            EmbeddingError,
            EMBEDDINGS_ENABLED,
        )

        query_vec: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                query_vec = await _embed_q(query)
            except (EmbeddingError, Exception) as exc:
                logger.debug("[KnowledgeGraph] Entity search embed failed: %s", exc)

        if query_vec is None:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if include_hierarchy:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'entity_embedding_idx', $limit, $vector"
                        ") YIELD node, score "
                        "OPTIONAL MATCH (node)-[:IS_A*1..3]->(anc:Entity) "
                        "RETURN node, score, collect(DISTINCT anc.name) AS ancestors",
                        vector=query_vec,
                        limit=limit,
                    )
                else:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'entity_embedding_idx', $limit, $vector"
                        ") YIELD node, score "
                        "RETURN node, score, [] AS ancestors",
                        vector=query_vec,
                        limit=limit,
                    )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Entity query failed: %s", exc)
                return []

        entities: List[Dict[str, Any]] = []
        for rec in records:
            node = rec["node"]
            entities.append(
                {
                    "id": node.get("id", ""),
                    "name": node.get("name", ""),
                    "entity_type": node.get("entity_type", ""),
                    "description": node.get("description", ""),
                    "mention_count": node.get("mention_count", 1),
                    "last_confirmed": node.get("last_confirmed", ""),
                    "confirmation_count": node.get("confirmation_count", 1),
                    "similarity": round(rec["score"], 4),
                    "ancestors": rec.get("ancestors") or [],
                }
            )
        return entities

    # ------------------------------------------------------------------
    # Relationship traversal
    # ------------------------------------------------------------------

    async def get_relationships(
        self,
        entity_ids: Optional[List[str]] = None,
        entity_names: Optional[List[str]] = None,
        max_hops: int = 1,
    ) -> List[Dict[str, Any]]:
        """
        Get relationships involving the given entities.

        Supports multi-hop traversal: hop 1 returns direct relationships,
        hop 2 adds relationships of the connected entities, etc.

        Either *entity_ids* or *entity_names* (or both) can be provided.
        Names are matched against the ``name`` property of Entity nodes.
        """
        if not self.available:
            return []

        assert self._driver is not None
        # Resolve entity_ids → names
        names: set[str] = set(entity_names or [])
        if entity_ids:
            async with self._driver.session(database=self._database) as session:
                try:
                    result = await session.run(
                        "MATCH (e:Entity) WHERE e.id IN $ids RETURN e.name AS name",
                        ids=entity_ids,
                    )
                    records = await result.data()
                    for rec in records:
                        if rec["name"]:
                            names.add(rec["name"])
                except Exception:
                    pass

        if not names:
            return []

        # Use variable-length Cypher path for multi-hop traversal.
        # Extract individual relationship properties directly in Cypher rather
        # than returning the relationship object itself — neo4j driver 5.x
        # serializes Relationship objects as (start_id, end_id, type, props)
        # tuples via .data(), not as plain dicts.
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (seed:Entity) WHERE seed.name IN $names "
                    "MATCH path = (seed)-[r:RELATES_TO*1.."
                    + str(max_hops)
                    + "]-(other:Entity) "
                    "UNWIND relationships(path) AS rel "
                    "WITH DISTINCT rel, startNode(rel) AS src, endNode(rel) AS tgt "
                    "RETURN rel.id AS rel_id, "
                    "       rel.relation_type AS relation_type, "
                    "       rel.confidence AS confidence, "
                    "       rel.evidence AS evidence, "
                    "       rel.session_id AS session_id, "
                    "       src.name AS source_entity, "
                    "       tgt.name AS target_entity",
                    names=list(names),
                )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Relationship traversal failed: %s", exc)
                return []

        seen_ids: set[str] = set()
        all_rels: List[Dict[str, Any]] = []
        for rec in records:
            rel_id = rec.get("rel_id") or ""
            if rel_id in seen_ids:
                continue
            seen_ids.add(rel_id)
            all_rels.append(
                {
                    "id": rel_id,
                    "source_entity": rec.get("source_entity", ""),
                    "target_entity": rec.get("target_entity", ""),
                    "relation_type": rec.get("relation_type", ""),
                    "confidence": rec.get("confidence", 0.0),
                    "evidence": rec.get("evidence", ""),
                    "session_id": rec.get("session_id", ""),
                }
            )
        return all_rels

    # ------------------------------------------------------------------
    # Community detection + summaries
    # ------------------------------------------------------------------

    async def get_communities(
        self, entity_ids: Optional[List[str]] = None
    ) -> List[Dict[str, Any]]:
        """Retrieve community summaries relevant to the given entities."""
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if entity_ids:
                    result = await session.run(
                        "MATCH (e:Entity)-[:MEMBER_OF]->(c:Community) "
                        "WHERE e.id IN $ids "
                        "RETURN DISTINCT c",
                        ids=entity_ids,
                    )
                else:
                    result = await session.run("MATCH (c:Community) RETURN c LIMIT 20")
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community fetch failed: %s", exc)
                return []

        communities: List[Dict[str, Any]] = []
        for rec in records:
            c = rec["c"]
            entity_id_list = json.loads(c.get("entity_ids", "[]"))
            communities.append(
                {
                    "id": c.get("id", ""),
                    "topic": c.get("topic", ""),
                    "summary": c.get("summary", ""),
                    "entity_ids": entity_id_list,
                    "created_at": c.get("created_at", ""),
                }
            )
        return communities

    async def update_communities(
        self,
        summarize_fn: Callable[[str], Coroutine[Any, Any, str]],
        max_communities: int = 10,
    ) -> int:
        """
        Detect entity communities by relationship co-occurrence and generate
        LLM summaries for each cluster.

        Parameters
        ----------
        summarize_fn:
            Async callable that takes a text prompt and returns an LLM-generated
            summary string.  Provided by the orchestrator to avoid coupling the
            graph layer to a specific LLM backend.
        max_communities:
            Maximum number of communities to process per call.  Prevents
            unbounded sequential LLM calls when the graph is large.

        Returns
        -------
        int
            Number of communities created or updated.
        """
        if not self.available:
            return 0

        clusters = await self._detect_clusters()
        if not clusters:
            return 0

        count = 0
        for cluster_entity_ids, cluster_names in clusters[:max_communities]:
            context = await self._build_cluster_context(
                cluster_entity_ids, cluster_names
            )
            if not context:
                continue

            prompt = (
                "Summarize the following cluster of related entities and their "
                "relationships into a concise paragraph. Focus on the key themes, "
                "connections, and implications:\n\n" + context
            )
            try:
                summary = await summarize_fn(prompt)
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community summarization failed: %s", exc)
                continue

            if not summary or not summary.strip():
                continue

            topic = ", ".join(sorted(cluster_names)[:3])

            community_vector: Optional[List[float]] = None
            try:
                from embeddings import (
                    embed_texts,
                    EmbeddingError,
                    EMBEDDINGS_ENABLED as _EE,
                )

                if _EE:
                    vecs = await embed_texts([summary.strip()])
                    community_vector = vecs[0] if vecs else None
            except Exception:
                pass

            await self._store_community(
                cluster_entity_ids, topic, summary.strip(), community_vector
            )
            count += 1

        logger.debug("[KnowledgeGraph] Updated %d communities.", count)
        return count

    async def _detect_clusters(self) -> List[tuple]:
        """
        Simple community detection: group entities that share >= N relationships.

        Returns list of (entity_id_list, entity_name_set) tuples.
        """
        assert self._driver is not None

        # Fetch adjacency from Neo4j in a single query
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (s:Entity)-[:RELATES_TO]-(t:Entity) "
                    "RETURN s.name AS source, t.name AS target"
                )
                records = await result.data()
            except Exception:
                return []

        if not records:
            return []

        # Build adjacency by entity name
        adjacency: Dict[str, set[str]] = defaultdict(set)
        for rec in records:
            src = rec["source"]
            tgt = rec["target"]
            if src and tgt:
                adjacency[src].add(tgt)
                adjacency[tgt].add(src)

        # Simple greedy clustering
        visited: set[str] = set()
        clusters: List[set[str]] = []

        for entity_name in adjacency:
            if entity_name in visited:
                continue
            cluster: set[str] = {entity_name}
            queue = [entity_name]
            while queue:
                current = queue.pop(0)
                for neighbor in adjacency.get(current, set()):
                    if neighbor in cluster:
                        continue
                    shared = len(adjacency.get(neighbor, set()) & cluster)
                    if shared >= _COMMUNITY_MIN_SHARED_RELS or len(cluster) == 1:
                        cluster.add(neighbor)
                        queue.append(neighbor)
            if len(cluster) >= 2:
                visited |= cluster
                clusters.append(cluster)

        # Resolve names → entity_ids
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (e:Entity) RETURN e.name AS name, e.id AS id"
                )
                records = await result.data()
            except Exception:
                return []

        name_to_id: Dict[str, str] = {}
        for rec in records:
            if rec["name"]:
                name_to_id[rec["name"]] = rec["id"]

        final: List[tuple] = []
        for cluster_names in clusters:
            ids = [name_to_id[n] for n in cluster_names if n in name_to_id]
            if len(ids) >= 2:
                final.append((ids, cluster_names))

        return final

    async def _build_cluster_context(
        self, entity_ids: List[str], entity_names: set[str]
    ) -> str:
        """Build a text context for community summarization."""
        assert self._driver is not None
        parts: List[str] = []

        async with self._driver.session(database=self._database) as session:
            # Entity descriptions
            try:
                result = await session.run(
                    "MATCH (e:Entity) WHERE e.id IN $ids "
                    "RETURN e.description AS desc",
                    ids=entity_ids,
                )
                records = await result.data()
                for rec in records:
                    if rec["desc"]:
                        parts.append(f"Entity: {rec['desc']}")
            except Exception:
                pass

            # Relationships between cluster members
            try:
                result = await session.run(
                    "MATCH (s:Entity)-[r:RELATES_TO]->(t:Entity) "
                    "WHERE s.name IN $names AND t.name IN $names "
                    "RETURN s.name AS src, r.relation_type AS rel, t.name AS tgt",
                    names=list(entity_names),
                )
                records = await result.data()
                for rec in records:
                    parts.append(
                        f"Relationship: {rec['src']} → {rec['rel']} → {rec['tgt']}"
                    )
            except Exception:
                pass

        return "\n".join(parts)

    async def _store_community(
        self,
        entity_ids: List[str],
        topic: str,
        summary: str,
        vector: Optional[List[float]] = None,
    ) -> None:
        """Store or update a community summary."""
        assert self._driver is not None
        now = datetime.now().isoformat()

        async with self._driver.session(database=self._database) as session:
            # Check if a community with overlapping entities already exists
            try:
                result = await session.run("MATCH (c:Community) RETURN c")
                records = await result.data()
                for rec in records:
                    c = rec["c"]
                    existing_ids = set(json.loads(c.get("entity_ids", "[]")))
                    overlap = len(existing_ids & set(entity_ids))
                    if overlap >= len(entity_ids) * 0.5:
                        # Update existing community
                        props: Dict[str, Any] = {
                            "entity_ids": json.dumps(entity_ids),
                            "topic": topic,
                            "summary": summary,
                            "updated_at": now,
                        }
                        if vector is not None:
                            props["embedding"] = vector
                        await session.run(
                            "MATCH (c:Community {id: $cid}) SET c += $props",
                            cid=c["id"],
                            props=props,
                        )
                        # Rebuild MEMBER_OF edges
                        await session.run(
                            "MATCH (c:Community {id: $cid})<-[r:MEMBER_OF]-() "
                            "DELETE r",
                            cid=c["id"],
                        )
                        await session.run(
                            "MATCH (c:Community {id: $cid}) "
                            "UNWIND $eids AS eid "
                            "MATCH (e:Entity {id: eid}) "
                            "MERGE (e)-[:MEMBER_OF]->(c)",
                            cid=c["id"],
                            eids=entity_ids,
                        )
                        return
            except Exception:
                pass

            # New community
            community_id = str(uuid.uuid4())
            try:
                props = {
                    "id": community_id,
                    "entity_ids": json.dumps(entity_ids),
                    "topic": topic,
                    "summary": summary,
                    "created_at": now,
                }
                if vector is not None:
                    props["embedding"] = vector
                await session.run(
                    "CREATE (c:Community) SET c = $props",
                    props=props,
                )
                # Create MEMBER_OF edges
                await session.run(
                    "MATCH (c:Community {id: $cid}) "
                    "UNWIND $eids AS eid "
                    "MATCH (e:Entity {id: eid}) "
                    "MERGE (e)-[:MEMBER_OF]->(c)",
                    cid=community_id,
                    eids=entity_ids,
                )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community store failed: %s", exc)

    # ------------------------------------------------------------------
    # Graph-aware recall (the main query interface)
    # ------------------------------------------------------------------

    async def recall_graph_context(
        self,
        query: str,
        entity_limit: int = 5,
        max_hops: int = 2,
        min_confidence: float = 0.0,
        include_contradictions: bool = False,
        include_provenance: bool = False,
    ) -> str:
        """
        Build a structured text context from the knowledge graph for a query.

        1. Vector-search entities relevant to the query
        2. Traverse 1–N hops of relationships from those entities
        3. Retrieve community summaries for the entity clusters
        4. Optionally append contradictions and source provenance
        5. Return formatted text

        Parameters
        ----------
        query:
            Natural-language query to seed entity search.
        entity_limit:
            Maximum number of seed entities to retrieve.
        max_hops:
            Relationship traversal depth (1 = direct only, 2 = one middle node).
        min_confidence:
            Only include RELATES_TO edges at or above this confidence score.
        include_contradictions:
            Append a KNOWN CONTRADICTIONS section when conflicts exist for
            the seed entities.
        include_provenance:
            Append a SOURCE PROVENANCE section listing source URLs for the
            seed entities.

        Returns an empty string if the graph has no relevant data.
        """
        if not self.available:
            return ""

        # Step 1: find seed entities
        entities = await self.find_entities(query, limit=entity_limit)
        if not entities:
            return ""

        entity_ids = [e["id"] for e in entities]
        entity_names = [e["name"] for e in entities]

        # Step 2: traverse relationships
        relationships = await self.get_relationships(
            entity_names=entity_names, max_hops=max_hops
        )

        # Step 3: get community summaries
        communities = await self.get_communities(entity_ids=entity_ids)

        # Step 4: format
        parts: List[str] = []

        if entities:
            parts.append("KNOWN ENTITIES:")
            for e in entities:
                line = f"  • {e['name']} ({e['entity_type']})"
                if e.get("mention_count", 1) > 1:
                    line += f" — seen {e['mention_count']}x"
                if e.get("ancestors"):
                    line += f" [is-a: {', '.join(e['ancestors'][:2])}]"
                parts.append(line)

        if relationships:
            parts.append("\nKNOWN RELATIONSHIPS:")
            seen_triples: set[str] = set()
            for r in relationships:
                # Filter by minimum confidence when specified
                if min_confidence > 0.0 and r.get("confidence", 1.0) < min_confidence:
                    continue
                triple = f"{r['source_entity']} → {r['relation_type']} → {r['target_entity']}"
                if triple in seen_triples:
                    continue
                seen_triples.add(triple)
                conf = r.get("confidence", 1.0)
                conf_str = f" (conf: {conf:.2f})" if conf < 0.8 else ""
                parts.append(f"  • {triple}{conf_str}")

        if communities:
            parts.append("\nTHEMATIC CLUSTERS:")
            for c in communities:
                parts.append(f"  [{c['topic']}] {c['summary']}")

        # Step 5 (optional): contradictions
        if include_contradictions:
            try:
                contradictions = await self.find_contradictions(
                    entity_names=entity_names, limit=5
                )
                if contradictions:
                    parts.append("\nKNOWN CONTRADICTIONS:")
                    for c in contradictions:
                        explanation = c.get("explanation") or "conflicting claims"
                        parts.append(
                            f"  ⚠ {c['entity_a']} / {c['entity_b']}: {explanation}"
                        )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Contradiction recall skipped: %s", exc)

        # Step 6 (optional): provenance
        if include_provenance:
            try:
                provenance = await self.get_provenance(entity_names=entity_names[:3])
                if provenance:
                    parts.append("\nSOURCE PROVENANCE:")
                    for p in provenance[:5]:
                        cred = p.get("credibility_score", 0.5)
                        parts.append(
                            f"  • {p['entity_name']} ← {p['source_url']}"
                            f" (credibility: {cred:.1f})"
                        )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Provenance recall skipped: %s", exc)

        return "\n".join(parts) if parts else ""

    # ------------------------------------------------------------------
    # Stats (for testing / monitoring)
    # ------------------------------------------------------------------

    async def stats(self) -> Dict[str, int]:
        """Return counts of all graph elements."""
        if not self.available:
            return {
                "entities": 0,
                "relationships": 0,
                "communities": 0,
                "contradictions": 0,
                "sources": 0,
                "hierarchies": 0,
            }

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "CALL { MATCH (e:Entity) RETURN count(e) AS c } "
                    "WITH c AS entities "
                    "CALL { MATCH ()-[r:RELATES_TO]->() RETURN count(r) AS c } "
                    "WITH entities, c AS relationships "
                    "CALL { MATCH (co:Community) RETURN count(co) AS c } "
                    "WITH entities, relationships, c AS communities "
                    "CALL { MATCH ()-[r:CONTRADICTS]->() RETURN count(r) AS c } "
                    "WITH entities, relationships, communities, c AS contradictions "
                    "CALL { MATCH (s:Source) RETURN count(s) AS c } "
                    "WITH entities, relationships, communities, contradictions, c AS sources "
                    "CALL { MATCH ()-[r:IS_A]->() RETURN count(r) AS c } "
                    "RETURN entities, relationships, communities, contradictions, "
                    "       sources, c AS hierarchies"
                )
                record = await result.single()
                if record:
                    return {
                        "entities": record["entities"],
                        "relationships": record["relationships"],
                        "communities": record["communities"],
                        "contradictions": record["contradictions"],
                        "sources": record["sources"],
                        "hierarchies": record["hierarchies"],
                    }
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Stats query failed: %s", exc)

        return {
            "entities": 0,
            "relationships": 0,
            "communities": 0,
            "contradictions": 0,
            "sources": 0,
            "hierarchies": 0,
        }

    # ------------------------------------------------------------------
    # Hierarchy (IS_A)
    # ------------------------------------------------------------------

    async def store_hierarchy(
        self,
        child_name: str,
        parent_name: str,
    ) -> Dict[str, Any]:
        """Create an IS_A edge from *child_name* to *parent_name* (idempotent).

        Both entities must already exist in the graph.  If either is missing
        the call is silently ignored (returns success=False).
        """
        if not self.available:
            return {"success": False, "message": "Graph not available"}
        if not child_name.strip() or not parent_name.strip():
            return {"success": False, "message": "Both names required"}
        if child_name.strip().lower() == parent_name.strip().lower():
            return {"success": False, "message": "Self-hierarchy not allowed"}

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (child:Entity {name: $child}) "
                    "MATCH (parent:Entity {name: $parent}) "
                    "MERGE (child)-[:IS_A]->(parent) "
                    "RETURN 'ok' AS result",
                    child=child_name.strip(),
                    parent=parent_name.strip(),
                )
                record = await result.single()
                if record:
                    return {"success": True}
                return {"success": False, "message": "One or both entities not found"}
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Hierarchy store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    # ------------------------------------------------------------------
    # Contradiction tracking
    # ------------------------------------------------------------------

    async def store_contradiction(
        self,
        rel_id_a: str,
        rel_id_b: str,
        explanation: str = "",
        session_id: str = "",
    ) -> Dict[str, Any]:
        """Record that two RELATES_TO relationships contradict each other.

        Creates a CONTRADICTS edge between the *source* entities of the two
        relationships, carrying both relationship IDs and an explanation so the
        planner can surface the conflict and design resolution steps.
        """
        if not self.available:
            return {"success": False, "message": "Graph not available"}

        assert self._driver is not None
        now = datetime.now().isoformat()
        cid = str(uuid.uuid4())

        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH ()-[r1:RELATES_TO {id: $id_a}]->() "
                    "MATCH ()-[r2:RELATES_TO {id: $id_b}]->() "
                    "WITH startNode(r1) AS e1, startNode(r2) AS e2 "
                    "CREATE (e1)-[:CONTRADICTS { "
                    "  id: $cid, rel_id_a: $id_a, rel_id_b: $id_b, "
                    "  explanation: $explanation, session_id: $session_id, "
                    "  created_at: $now "
                    "}]->(e2) "
                    "RETURN 'ok' AS result",
                    id_a=rel_id_a,
                    id_b=rel_id_b,
                    cid=cid,
                    explanation=explanation.strip(),
                    session_id=session_id,
                    now=now,
                )
                record = await result.single()
                if record:
                    return {"success": True, "contradiction_id": cid}
                return {
                    "success": False,
                    "message": "One or both relationship IDs not found",
                }
            except Exception as exc:
                logger.error("[KnowledgeGraph] Contradiction store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    async def find_contradictions(
        self,
        entity_names: Optional[List[str]] = None,
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Return CONTRADICTS edges involving the given entities (or all if None)."""
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if entity_names:
                    result = await session.run(
                        "MATCH (e1:Entity)-[c:CONTRADICTS]->(e2:Entity) "
                        "WHERE e1.name IN $names OR e2.name IN $names "
                        "OPTIONAL MATCH ()-[r1:RELATES_TO {id: c.rel_id_a}]->() "
                        "OPTIONAL MATCH ()-[r2:RELATES_TO {id: c.rel_id_b}]->() "
                        "RETURN e1.name AS entity_a, e2.name AS entity_b, "
                        "       c.explanation AS explanation, c.id AS id, "
                        "       r1.relation_type AS rel_a_type, "
                        "       r1.evidence AS rel_a_evidence, "
                        "       r2.relation_type AS rel_b_type, "
                        "       r2.evidence AS rel_b_evidence "
                        "LIMIT $limit",
                        names=entity_names,
                        limit=limit,
                    )
                else:
                    result = await session.run(
                        "MATCH (e1:Entity)-[c:CONTRADICTS]->(e2:Entity) "
                        "OPTIONAL MATCH ()-[r1:RELATES_TO {id: c.rel_id_a}]->() "
                        "OPTIONAL MATCH ()-[r2:RELATES_TO {id: c.rel_id_b}]->() "
                        "RETURN e1.name AS entity_a, e2.name AS entity_b, "
                        "       c.explanation AS explanation, c.id AS id, "
                        "       r1.relation_type AS rel_a_type, "
                        "       r1.evidence AS rel_a_evidence, "
                        "       r2.relation_type AS rel_b_type, "
                        "       r2.evidence AS rel_b_evidence "
                        "LIMIT $limit",
                        limit=limit,
                    )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Contradiction query failed: %s", exc)
                return []

        return [
            {
                "id": rec.get("id", ""),
                "entity_a": rec.get("entity_a", ""),
                "entity_b": rec.get("entity_b", ""),
                "explanation": rec.get("explanation", ""),
                "rel_a_type": rec.get("rel_a_type", ""),
                "rel_a_evidence": rec.get("rel_a_evidence", ""),
                "rel_b_type": rec.get("rel_b_type", ""),
                "rel_b_evidence": rec.get("rel_b_evidence", ""),
            }
            for rec in records
        ]

    # ------------------------------------------------------------------
    # Source provenance
    # ------------------------------------------------------------------

    async def store_source(
        self,
        url: str,
        title: str = "",
        credibility_score: float = 0.5,
    ) -> Dict[str, Any]:
        """Upsert a Source node (unique by URL).

        On conflict, title is updated only if the new value is non-empty;
        credibility_score is updated to the higher of the two values.
        """
        if not self.available:
            return {"success": False, "message": "Graph not available"}
        if not url or not url.strip().startswith("http"):
            return {"success": False, "message": "Invalid URL"}

        assert self._driver is not None
        from urllib.parse import urlparse

        domain = urlparse(url.strip()).netloc or ""
        now = datetime.now().isoformat()

        async with self._driver.session(database=self._database) as session:
            try:
                await session.run(
                    "MERGE (s:Source {url: $url}) "
                    "ON CREATE SET s.title = $title, "
                    "              s.credibility_score = $credibility_score, "
                    "              s.domain = $domain, "
                    "              s.first_seen = $now "
                    "ON MATCH SET  s.title = CASE WHEN $title <> '' THEN $title ELSE s.title END, "
                    "              s.credibility_score = CASE "
                    "                WHEN $credibility_score > s.credibility_score "
                    "                THEN $credibility_score ELSE s.credibility_score END",
                    url=url.strip(),
                    title=title.strip(),
                    credibility_score=credibility_score,
                    domain=domain,
                    now=now,
                )
                return {"success": True, "url": url.strip()}
            except Exception as exc:
                logger.error("[KnowledgeGraph] Source store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    async def link_to_source(
        self,
        entity_name: str,
        source_url: str,
    ) -> Dict[str, Any]:
        """Create a SOURCED_FROM edge from an Entity to a Source node."""
        if not self.available:
            return {"success": False, "message": "Graph not available"}

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (e:Entity {name: $name}) "
                    "MATCH (s:Source {url: $url}) "
                    "MERGE (e)-[:SOURCED_FROM]->(s) "
                    "RETURN 'ok' AS result",
                    name=entity_name.strip(),
                    url=source_url.strip(),
                )
                record = await result.single()
                if record:
                    return {"success": True}
                return {"success": False, "message": "Entity or source not found"}
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Source link failed: %s", exc)
                return {"success": False, "message": str(exc)}

    async def get_provenance(
        self,
        entity_names: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """Return source nodes linked to the given entities via SOURCED_FROM."""
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if entity_names:
                    result = await session.run(
                        "MATCH (e:Entity)-[:SOURCED_FROM]->(s:Source) "
                        "WHERE e.name IN $names "
                        "RETURN e.name AS entity_name, s.url AS source_url, "
                        "       s.title AS source_title, "
                        "       s.credibility_score AS credibility_score, "
                        "       s.domain AS domain",
                        names=entity_names,
                    )
                else:
                    result = await session.run(
                        "MATCH (e:Entity)-[:SOURCED_FROM]->(s:Source) "
                        "RETURN e.name AS entity_name, s.url AS source_url, "
                        "       s.title AS source_title, "
                        "       s.credibility_score AS credibility_score, "
                        "       s.domain AS domain "
                        "LIMIT 50"
                    )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Provenance query failed: %s", exc)
                return []

        return [
            {
                "entity_name": rec.get("entity_name", ""),
                "source_url": rec.get("source_url", ""),
                "source_title": rec.get("source_title", ""),
                "credibility_score": rec.get("credibility_score", 0.0),
                "domain": rec.get("domain", ""),
            }
            for rec in records
        ]

    # ------------------------------------------------------------------
    # Temporal / recency queries
    # ------------------------------------------------------------------

    async def recent_entities(
        self,
        since_date: Optional[str] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Return entities added or confirmed since the given ISO-8601 date string.

        If *since_date* is None the most recently confirmed entities are
        returned regardless of age.
        """
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if since_date:
                    result = await session.run(
                        "MATCH (e:Entity) "
                        "WHERE e.last_confirmed >= $since_date "
                        "RETURN e ORDER BY e.last_confirmed DESC LIMIT $limit",
                        since_date=since_date,
                        limit=limit,
                    )
                else:
                    result = await session.run(
                        "MATCH (e:Entity) "
                        "RETURN e ORDER BY e.last_confirmed DESC LIMIT $limit",
                        limit=limit,
                    )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] recent_entities failed: %s", exc)
                return []

        return [
            {
                "id": rec["e"].get("id", ""),
                "name": rec["e"].get("name", ""),
                "entity_type": rec["e"].get("entity_type", ""),
                "mention_count": rec["e"].get("mention_count", 1),
                "last_confirmed": rec["e"].get("last_confirmed", ""),
            }
            for rec in records
        ]

    async def recent_relationships(
        self,
        since_date: Optional[str] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Return RELATES_TO edges created or confirmed since *since_date*."""
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if since_date:
                    result = await session.run(
                        "MATCH (s:Entity)-[r:RELATES_TO]->(t:Entity) "
                        "WHERE r.last_confirmed >= $since_date "
                        "RETURN s.name AS source_entity, r.relation_type AS relation_type, "
                        "       t.name AS target_entity, r.confidence AS confidence, "
                        "       r.last_confirmed AS last_confirmed "
                        "ORDER BY r.last_confirmed DESC LIMIT $limit",
                        since_date=since_date,
                        limit=limit,
                    )
                else:
                    result = await session.run(
                        "MATCH (s:Entity)-[r:RELATES_TO]->(t:Entity) "
                        "RETURN s.name AS source_entity, r.relation_type AS relation_type, "
                        "       t.name AS target_entity, r.confidence AS confidence, "
                        "       r.last_confirmed AS last_confirmed "
                        "ORDER BY r.last_confirmed DESC LIMIT $limit",
                        limit=limit,
                    )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] recent_relationships failed: %s", exc)
                return []

        return [
            {
                "source_entity": rec.get("source_entity", ""),
                "relation_type": rec.get("relation_type", ""),
                "target_entity": rec.get("target_entity", ""),
                "confidence": rec.get("confidence", 0.0),
                "last_confirmed": rec.get("last_confirmed", ""),
            }
            for rec in records
        ]

    async def session_diff(
        self,
        session_id: str,
    ) -> Dict[str, List[Dict[str, Any]]]:
        """Return entities and relationships created during a specific session."""
        if not self.available or not session_id:
            return {"entities": [], "relationships": []}

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                ent_result = await session.run(
                    "MATCH (e:Entity) "
                    "WHERE $session_id IN e.source_sessions OR "
                    "      e.source_sessions CONTAINS $session_id "
                    "RETURN e.name AS name, e.entity_type AS entity_type, "
                    "       e.description AS description",
                    session_id=session_id,
                )
                entities = [
                    {
                        "name": r.get("name", ""),
                        "entity_type": r.get("entity_type", ""),
                        "description": r.get("description", ""),
                    }
                    for r in await ent_result.data()
                ]

                rel_result = await session.run(
                    "MATCH (s:Entity)-[r:RELATES_TO]->(t:Entity) "
                    "WHERE r.session_id = $session_id "
                    "RETURN s.name AS source_entity, r.relation_type AS relation_type, "
                    "       t.name AS target_entity, r.confidence AS confidence",
                    session_id=session_id,
                )
                relationships = [
                    {
                        "source_entity": r.get("source_entity", ""),
                        "relation_type": r.get("relation_type", ""),
                        "target_entity": r.get("target_entity", ""),
                        "confidence": r.get("confidence", 0.0),
                    }
                    for r in await rel_result.data()
                ]
            except Exception as exc:
                logger.debug("[KnowledgeGraph] session_diff failed: %s", exc)
                return {"entities": [], "relationships": []}

        return {"entities": entities, "relationships": relationships}

    # ------------------------------------------------------------------
    # Graph path queries
    # ------------------------------------------------------------------

    async def find_paths(
        self,
        source_name: str,
        target_name: str,
        max_depth: int = 4,
    ) -> List[Dict[str, Any]]:
        """Find shortest paths between two named entities.

        Traverses both RELATES_TO and IS_A edges.  Returns up to 5 paths,
        each as a dict with ``node_names`` (ordered list of entity names along
        the path) and ``path_length``.

        Returns [] if no path exists within *max_depth* hops or either entity
        is not in the graph.
        """
        if not self.available:
            return []
        if not source_name.strip() or not target_name.strip():
            return []
        # Guard: max_depth bounds to prevent combinatorial explosion
        max_depth = min(max_depth, 6)

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (src:Entity {name: $source}), (tgt:Entity {name: $target}) "
                    "MATCH p = shortestPath("
                    "  (src)-[:RELATES_TO|IS_A*1.." + str(max_depth) + "]-(tgt)"
                    ") "
                    "RETURN [n IN nodes(p) | n.name] AS node_names, "
                    "       length(p) AS path_length "
                    "LIMIT 5",
                    source=source_name.strip(),
                    target=target_name.strip(),
                )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] find_paths failed: %s", exc)
                return []

        return [
            {
                "node_names": rec.get("node_names", []),
                "path_length": rec.get("path_length", 0),
            }
            for rec in records
        ]

    async def find_common_neighbors(
        self,
        entity_names: List[str],
        min_shared: int = 2,
    ) -> List[Dict[str, Any]]:
        """Return entities connected to at least *min_shared* of the named entities.

        Useful for surfacing hidden bridge concepts that link multiple seed
        entities without being directly listed as results.
        """
        if not self.available or not entity_names:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (seed:Entity)-[:RELATES_TO]-(common:Entity) "
                    "WHERE seed.name IN $names AND NOT common.name IN $names "
                    "WITH common, count(DISTINCT seed) AS shared_count "
                    "WHERE shared_count >= $min_shared "
                    "RETURN common.name AS name, common.entity_type AS entity_type, "
                    "       common.description AS description, shared_count "
                    "ORDER BY shared_count DESC LIMIT 10",
                    names=entity_names,
                    min_shared=min_shared,
                )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] find_common_neighbors failed: %s", exc)
                return []

        return [
            {
                "name": rec.get("name", ""),
                "entity_type": rec.get("entity_type", ""),
                "description": rec.get("description", ""),
                "shared_connections": rec.get("shared_count", 0),
            }
            for rec in records
        ]

    # ------------------------------------------------------------------
    # Confidence decay
    # ------------------------------------------------------------------

    async def decay_confidence(
        self,
        half_life_days: int = 30,
    ) -> int:
        """Exponentially decay the confidence of RELATES_TO edges not confirmed recently.

        Uses the formula: ``new_confidence = confidence × 2^(−days_since_confirmed / half_life)``

        Edges with ``last_confirmed`` set to NULL are skipped (no decay applied
        to legacy edges that predate temporal tracking).  Confidence is floored
        at 0.01 to prevent complete erasure.

        Returns the number of edges updated.
        """
        if not self.available or half_life_days <= 0:
            return 0

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH ()-[r:RELATES_TO]->() "
                    "WHERE r.last_confirmed IS NOT NULL "
                    "WITH r, "
                    "     toInteger("
                    "       (datetime().epochSeconds "
                    "        - datetime(r.last_confirmed).epochSeconds) / 86400"
                    "     ) AS days_old "
                    "WHERE days_old > 0 "
                    "WITH r, days_old, "
                    "     r.confidence * exp(-0.693 * toFloat(days_old) / $half_life) "
                    "     AS decayed "
                    "SET r.confidence = CASE WHEN decayed < 0.01 THEN 0.01 ELSE decayed END "
                    "RETURN count(r) AS updated",
                    half_life=float(half_life_days),
                )
                record = await result.single()
                return record["updated"] if record else 0
            except Exception as exc:
                logger.debug("[KnowledgeGraph] decay_confidence failed: %s", exc)
                return 0

    # ------------------------------------------------------------------
    # Graph pruning
    # ------------------------------------------------------------------

    async def prune(
        self,
        min_confidence: float = 0.1,
        max_age_days: int = 180,
        dry_run: bool = True,
    ) -> Dict[str, int]:
        """Remove stale, low-confidence graph elements.

        Prunes in three passes:

        1. **Stale relationships** — RELATES_TO edges where confidence has
           decayed below *min_confidence* OR where ``last_confirmed`` is more
           than *max_age_days* old.
        2. **Orphaned entities** — Entity nodes left with no RELATES_TO,
           IS_A, SOURCED_FROM, or MEMBER_OF edges after pass 1.
        3. **Dangling CONTRADICTS edges** — CONTRADICTS edges whose referenced
           ``rel_id_a`` / ``rel_id_b`` no longer exist in the graph.

        Parameters
        ----------
        min_confidence:
            Delete RELATES_TO edges whose confidence has fallen below this
            floor (after decay).  Default 0.1.
        max_age_days:
            Delete RELATES_TO edges whose ``last_confirmed`` timestamp is
            older than this many days, regardless of confidence.  Set to 0 to
            disable age-based pruning.  Default 180.
        dry_run:
            When True (default) only *counts* what would be deleted without
            actually removing anything.  Set to False to execute the deletes.

        Returns
        -------
        dict with keys ``relationships``, ``entities``, ``contradictions``
        containing the count of items deleted (or would-be-deleted in dry_run).
        """
        if not self.available:
            return {"relationships": 0, "entities": 0, "contradictions": 0}

        assert self._driver is not None
        results: Dict[str, int] = {
            "relationships": 0,
            "entities": 0,
            "contradictions": 0,
        }

        async with self._driver.session(database=self._database) as session:
            # ── Pass 1: stale relationships ────────────────────────────────
            try:
                age_clause = ""
                params: Dict[str, Any] = {"min_conf": min_confidence}
                if max_age_days > 0:
                    params["max_age_days"] = float(max_age_days)
                    age_clause = (
                        " OR ("
                        "r.last_confirmed IS NOT NULL AND "
                        "toInteger("
                        "  (datetime().epochSeconds "
                        "   - datetime(r.last_confirmed).epochSeconds) / 86400"
                        ") > $max_age_days"
                        ")"
                    )

                count_q = (
                    "MATCH ()-[r:RELATES_TO]->() "
                    f"WHERE r.confidence < $min_conf{age_clause} "
                    "RETURN count(r) AS cnt"
                )
                cnt_result = await session.run(count_q, **params)
                cnt_record = await cnt_result.single()
                rel_count = cnt_record["cnt"] if cnt_record else 0
                results["relationships"] = rel_count

                if not dry_run and rel_count > 0:
                    delete_q = (
                        "MATCH ()-[r:RELATES_TO]->() "
                        f"WHERE r.confidence < $min_conf{age_clause} "
                        "DELETE r"
                    )
                    await session.run(delete_q, **params)
                    logger.info(
                        "[KnowledgeGraph] Pruned %d stale relationships.", rel_count
                    )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] prune (relationships) failed: %s", exc)

            # ── Pass 2: orphaned entities ─────────────────────────────────
            try:
                orphan_q = (
                    "MATCH (e:Entity) "
                    "WHERE NOT (e)-[:RELATES_TO]-() "
                    "  AND NOT (e)-[:IS_A]-() "
                    "  AND NOT (e)-[:SOURCED_FROM]->() "
                    "  AND NOT (e)-[:MEMBER_OF]->() "
                    "RETURN count(e) AS cnt"
                )
                cnt_result = await session.run(orphan_q)
                cnt_record = await cnt_result.single()
                ent_count = cnt_record["cnt"] if cnt_record else 0
                results["entities"] = ent_count

                if not dry_run and ent_count > 0:
                    await session.run(
                        "MATCH (e:Entity) "
                        "WHERE NOT (e)-[:RELATES_TO]-() "
                        "  AND NOT (e)-[:IS_A]-() "
                        "  AND NOT (e)-[:SOURCED_FROM]->() "
                        "  AND NOT (e)-[:MEMBER_OF]->() "
                        "DELETE e"
                    )
                    logger.info(
                        "[KnowledgeGraph] Pruned %d orphaned entities.", ent_count
                    )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] prune (entities) failed: %s", exc)

            # ── Pass 3: dangling CONTRADICTS edges ─────────────────────────
            try:
                dangle_q = (
                    "MATCH (e1:Entity)-[c:CONTRADICTS]->(e2:Entity) "
                    "WHERE NOT EXISTS { MATCH ()-[r:RELATES_TO {id: c.rel_id_a}]->() } "
                    "   OR NOT EXISTS { MATCH ()-[r:RELATES_TO {id: c.rel_id_b}]->() } "
                    "RETURN count(c) AS cnt"
                )
                cnt_result = await session.run(dangle_q)
                cnt_record = await cnt_result.single()
                contra_count = cnt_record["cnt"] if cnt_record else 0
                results["contradictions"] = contra_count

                if not dry_run and contra_count > 0:
                    await session.run(
                        "MATCH (e1:Entity)-[c:CONTRADICTS]->(e2:Entity) "
                        "WHERE NOT EXISTS { MATCH ()-[r:RELATES_TO {id: c.rel_id_a}]->() } "
                        "   OR NOT EXISTS { MATCH ()-[r:RELATES_TO {id: c.rel_id_b}]->() } "
                        "DELETE c"
                    )
                    logger.info(
                        "[KnowledgeGraph] Pruned %d dangling contradiction edges.",
                        contra_count,
                    )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] prune (contradictions) failed: %s", exc)

        return results
