"""
long_term_memory.py

Persistent cross-session memory store backed by Neo4j, with an integrated
knowledge graph (GraphRAG) for capturing relationships between facts.

Replaces the standalone memory MCP server (mcp/memory/) by running the same
persistence logic in-process alongside the FastAPI backend.  Embedding is
handled by the shared embeddings.py module (sentence-transformers +
ThreadPoolExecutor), so there is exactly one model instance and one thread-pool
in the process.

Neo4j's native graph model stores entities and relationships as first-class
graph primitives, and its built-in vector indexes (since 5.11) provide cosine-
similarity ranking for embedding-based semantic search.

Architecture
------------
The store has two layers:

1. **Flat memory store** (``Memory`` nodes): raw text blobs with cosine
   similarity ranking via a Neo4j vector index.  Used for raw evidence
   persistence and simple semantic search.

2. **Knowledge graph** (``KnowledgeGraph``): Entity and Community nodes with
   ``RELATES_TO`` and ``MEMBER_OF`` relationships.  Used for relationship-aware
   recall that can follow multi-hop entity connections and surface structural
   knowledge across research sessions.

Public API
----------
  async_init()                               → None  (call once after event loop starts)
  store(content, category, importance, tags) → Dict
  find_similar(query, limit, min_similarity) → List[Dict]
  recall(query, category, min_importance,    → List[Dict]
         limit, similarity_threshold)

Graph API (via .graph attribute)
---------------------------------
  graph.upsert_entity(name, entity_type, description, session_id)  → Dict
  graph.store_relationship(source, target, relation, evidence, ...) → Dict
  graph.find_entities(query, limit)                                 → List[Dict]
  graph.get_relationships(entity_ids, max_hops)                     → List[Dict]
  graph.get_communities(entity_ids)                                 → List[Dict]
  graph.update_communities(summarize_fn)                            → int
  graph.recall_graph_context(query, entity_limit, max_hops)        → str
"""

from __future__ import annotations

import json
import logging
import uuid
from collections import defaultdict
from datetime import datetime
from typing import Any, Callable, Coroutine, Dict, List, Optional

import neo4j
from neo4j import AsyncGraphDatabase

logger = logging.getLogger(__name__)

# Cosine similarity threshold above which a candidate is considered a
# near-duplicate of an already-stored memory.
_DEDUP_THRESHOLD: float = 0.95

# Cosine similarity threshold for entity deduplication — entities with names
# that embed above this are considered the same entity and merged.
_ENTITY_DEDUP_THRESHOLD: float = 0.92

# Minimum number of shared relationships for two entities to be grouped
# into the same community during community detection.
_COMMUNITY_MIN_SHARED_RELS: int = 2


class AsyncLongTermMemory:
    """
    Async, in-process persistent memory store backed by Neo4j.

    Embeddings are generated by the shared ``embeddings.py`` module and stored
    as properties on Neo4j nodes.  Vector indexes provide cosine-similarity
    search over those embeddings.

    Usage
    -----
    ltm = AsyncLongTermMemory(neo4j_uri="bolt://localhost:7687")
    await ltm.async_init()   # call once, after the event loop is running

    await ltm.store("Key finding: X is true", category="research_finding", importance=7)
    memories = await ltm.find_similar("what do we know about X?", limit=5)
    """

    def __init__(
        self,
        neo4j_uri: str = "bolt://localhost:7687",
        neo4j_user: str = "neo4j",
        neo4j_password: str = "research_pass",
        neo4j_database: str = "neo4j",
        embedding_dimensions: int = 384,
    ) -> None:
        self._uri = neo4j_uri
        self._user = neo4j_user
        self._password = neo4j_password
        self._database = neo4j_database
        self._embedding_dimensions = embedding_dimensions
        self._driver: Optional[neo4j.AsyncDriver] = None
        # Set to False if async_init() fails (Neo4j unavailable); all
        # public methods become no-ops so the research pipeline is unaffected.
        self._available: bool = False
        # Knowledge graph layer — shares the same Neo4j driver.
        self.graph: KnowledgeGraph = KnowledgeGraph(self)

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    async def async_init(self) -> None:
        """Initialize the Neo4j driver, constraints, and vector indexes.

        Must be called once after the asyncio event loop is running (e.g. from
        the FastAPI lifespan handler).  Idempotent — safe to call multiple times.

        Failures are logged as warnings rather than raised so that an unavailable
        Neo4j instance never blocks server startup.  When init fails, all public
        methods silently return empty results.
        """
        try:
            self._driver = AsyncGraphDatabase.driver(
                self._uri, auth=(self._user, self._password)
            )
            await self._driver.verify_connectivity()
            await self._create_schema()
            self._available = True
            logger.info(
                "[LongTermMemory] Ready — uri=%s  database=%s",
                self._uri,
                self._database,
            )
        except Exception as exc:
            logger.warning(
                "[LongTermMemory] Initialization failed — long-term memory will be "
                "disabled for this session.  Cause: %s",
                exc,
            )

    async def _create_schema(self) -> None:
        """Create uniqueness constraints and vector indexes (idempotent)."""
        assert self._driver is not None
        dims = self._embedding_dimensions
        async with self._driver.session(database=self._database) as session:
            # Uniqueness constraints
            await session.run(
                "CREATE CONSTRAINT memory_id IF NOT EXISTS "
                "FOR (m:Memory) REQUIRE m.id IS UNIQUE"
            )
            await session.run(
                "CREATE CONSTRAINT entity_id IF NOT EXISTS "
                "FOR (e:Entity) REQUIRE e.id IS UNIQUE"
            )
            await session.run(
                "CREATE CONSTRAINT community_id IF NOT EXISTS "
                "FOR (c:Community) REQUIRE c.id IS UNIQUE"
            )
            # Vector indexes for cosine similarity search
            await session.run(
                "CREATE VECTOR INDEX memory_embedding_idx IF NOT EXISTS "
                "FOR (m:Memory) ON (m.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )
            await session.run(
                "CREATE VECTOR INDEX entity_embedding_idx IF NOT EXISTS "
                "FOR (e:Entity) ON (e.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )
            await session.run(
                "CREATE VECTOR INDEX community_embedding_idx IF NOT EXISTS "
                "FOR (c:Community) ON (c.embedding) "
                "OPTIONS {indexConfig: {`vector.dimensions`: $dims, "
                "`vector.similarity_function`: 'cosine'}}",
                dims=dims,
            )

    async def close(self) -> None:
        """Close the Neo4j driver.  Call during application shutdown."""
        if self._driver is not None:
            await self._driver.close()
            self._driver = None
            self._available = False

    # ------------------------------------------------------------------
    # Public async API
    # ------------------------------------------------------------------

    async def store(
        self,
        content: str,
        category: str = "general",
        importance: int = 5,
        tags: Optional[List[str]] = None,
        extra_metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Store a memory.  Returns ``{"success": False}`` if LTM is unavailable."""
        if not self._available:
            return {"success": False, "message": "LongTermMemory not available"}

        if not content or not content.strip():
            return {"success": False, "message": "Empty content"}

        from embeddings import embed_texts, EmbeddingError, EMBEDDINGS_ENABLED

        vector: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                vecs = await embed_texts([content])
                vector = vecs[0] if vecs else None
            except EmbeddingError as exc:
                logger.debug(
                    "[LongTermMemory] Embedding unavailable for store: %s", exc
                )
            except Exception as exc:
                logger.debug(
                    "[LongTermMemory] Unexpected embed error in store: %s", exc
                )

        assert self._driver is not None
        memory_id = str(uuid.uuid4())
        now = datetime.now().isoformat()
        tags_list = tags or []
        extra = extra_metadata or {}

        async with self._driver.session(database=self._database) as session:
            try:
                # Dedup check via vector similarity
                if vector is not None:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'memory_embedding_idx', 1, $vector"
                        ") YIELD node, score "
                        "WHERE score >= $threshold "
                        "RETURN node.id AS id, score",
                        vector=vector,
                        threshold=_DEDUP_THRESHOLD,
                    )
                    record = await result.single()
                    if record:
                        return {
                            "success": False,
                            "memory_id": record["id"],
                            "message": (
                                f"Near-duplicate already stored "
                                f"(similarity={record['score']:.3f})"
                            ),
                        }

                # Build the CREATE query
                props: Dict[str, Any] = {
                    "id": memory_id,
                    "content": content,
                    "category": category,
                    "importance": importance,
                    "created_at": now,
                    "last_accessed": now,
                    "access_count": 0,
                    "tags": json.dumps(tags_list),
                }
                for k, v in extra.items():
                    props[f"custom_{k}"] = (
                        json.dumps(v) if isinstance(v, (list, dict)) else v
                    )
                if vector is not None:
                    props["embedding"] = vector

                await session.run(
                    "CREATE (m:Memory) SET m = $props",
                    props=props,
                )
                return {"success": True, "memory_id": memory_id, "message": "Stored"}

            except Exception as exc:
                logger.error("[LongTermMemory] store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    async def find_similar(
        self,
        query: str,
        limit: int = 5,
        min_similarity: float = 0.7,
    ) -> List[Dict[str, Any]]:
        """Find memories semantically similar to *query*. Returns [] if LTM unavailable."""
        if not self._available:
            return []
        return await self.recall(
            query=query,
            limit=limit,
            similarity_threshold=min_similarity,
        )

    async def recall(
        self,
        query: Optional[str] = None,
        category: Optional[str] = None,
        min_importance: Optional[int] = None,
        limit: int = 10,
        similarity_threshold: float = 0.0,
    ) -> List[Dict[str, Any]]:
        """Recall memories via semantic search.  Returns [] if LTM unavailable."""
        if not self._available:
            return []

        if not query:
            return await self._recall_no_query(category, min_importance, limit)

        from embeddings import (
            embed_query as _embed_q,
            EmbeddingError,
            EMBEDDINGS_ENABLED,
        )

        query_vec: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                query_vec = await _embed_q(query)
            except EmbeddingError as exc:
                logger.debug(
                    "[LongTermMemory] Embedding unavailable for recall: %s", exc
                )
            except Exception as exc:
                logger.debug(
                    "[LongTermMemory] Unexpected embed error in recall: %s", exc
                )

        if query_vec is None:
            return await self._recall_no_query(category, min_importance, limit)

        return await self._recall_with_vector(
            query_vec, category, min_importance, limit, similarity_threshold
        )

    # ------------------------------------------------------------------
    # Internal recall helpers
    # ------------------------------------------------------------------

    async def _recall_with_vector(
        self,
        query_vec: List[float],
        category: Optional[str],
        min_importance: Optional[int],
        limit: int,
        similarity_threshold: float,
    ) -> List[Dict[str, Any]]:
        assert self._driver is not None
        # Fetch more than needed to allow post-filtering
        fetch_limit = limit * 2

        where_parts: List[str] = []
        params: Dict[str, Any] = {
            "vector": query_vec,
            "fetch_limit": fetch_limit,
            "threshold": similarity_threshold,
        }
        if category:
            where_parts.append("node.category = $category")
            params["category"] = category
        if min_importance is not None:
            where_parts.append("node.importance >= $min_importance")
            params["min_importance"] = min_importance

        where_clause = ""
        if where_parts:
            where_clause = " AND " + " AND ".join(where_parts)

        cypher = (
            "CALL db.index.vector.queryNodes("
            "  'memory_embedding_idx', $fetch_limit, $vector"
            ") YIELD node, score "
            f"WHERE score >= $threshold{where_clause} "
            "RETURN node, score "
            "ORDER BY node.importance * score DESC "
            "LIMIT $limit"
        )
        params["limit"] = limit

        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(cypher, **params)
                records = await result.data()
            except Exception as exc:
                logger.debug("[LongTermMemory] recall query failed: %s", exc)
                return []

        now = datetime.now().isoformat()
        memories: List[Dict[str, Any]] = []
        update_ids: List[str] = []

        for rec in records:
            node = rec["node"]
            score = rec["score"]
            memories.append(self._unpack(node, score))
            update_ids.append(node["id"])

        # Batch-update access stats (best-effort)
        if update_ids:
            try:
                async with self._driver.session(database=self._database) as session:
                    await session.run(
                        "UNWIND $ids AS mid "
                        "MATCH (m:Memory {id: mid}) "
                        "SET m.last_accessed = $now, "
                        "    m.access_count = m.access_count + 1",
                        ids=update_ids,
                        now=now,
                    )
            except Exception:
                pass

        return memories

    async def _recall_no_query(
        self,
        category: Optional[str],
        min_importance: Optional[int],
        limit: int,
    ) -> List[Dict[str, Any]]:
        assert self._driver is not None

        where_parts: List[str] = []
        params: Dict[str, Any] = {"limit": limit}
        if category:
            where_parts.append("m.category = $category")
            params["category"] = category
        if min_importance is not None:
            where_parts.append("m.importance >= $min_importance")
            params["min_importance"] = min_importance

        where_clause = " WHERE " + " AND ".join(where_parts) if where_parts else ""
        cypher = f"MATCH (m:Memory){where_clause} RETURN m LIMIT $limit"

        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(cypher, **params)
                records = await result.data()
            except Exception as exc:
                logger.debug("[LongTermMemory] recall (no query) failed: %s", exc)
                return []

        return [self._unpack(rec["m"], 0.0) for rec in records]

    @staticmethod
    def _unpack(node: Dict[str, Any], score: float) -> Dict[str, Any]:
        tags = json.loads(node.get("tags", "[]"))
        custom: Dict[str, Any] = {}
        for k, v in node.items():
            if k.startswith("custom_"):
                try:
                    custom[k[7:]] = json.loads(v)
                except Exception:
                    custom[k[7:]] = v
        return {
            "id": node.get("id"),
            "content": node.get("content"),
            "category": node.get("category"),
            "importance": node.get("importance"),
            "created_at": node.get("created_at"),
            "last_accessed": node.get("last_accessed"),
            "access_count": node.get("access_count", 0),
            "tags": tags,
            "metadata": custom or None,
            "similarity": round(score, 4),
        }


# ---------------------------------------------------------------------------
# Knowledge Graph (GraphRAG)
# ---------------------------------------------------------------------------


class KnowledgeGraph:
    """
    Relationship-aware knowledge graph stored natively in Neo4j.

    Three node types:

    * **Entity**: Named concepts, people, technologies, organizations.
      Embedded by ``name + ": " + description`` so semantic search finds
      entities by meaning, not just exact name match.

    * **RELATES_TO relationships**: Directed edges ``source → relation → target``
      with evidence text.  Stored as native Neo4j relationships for efficient
      multi-hop traversal.

    * **Community**: LLM-generated summaries of densely-connected entity
      clusters, linked via ``MEMBER_OF`` edges.  Updated as a post-synthesis
      background task.

    All public methods are async.  The ``_ltm`` back-reference provides access
    to the ``_available`` flag and the Neo4j driver.
    """

    def __init__(self, ltm: AsyncLongTermMemory) -> None:
        self._ltm = ltm

    @property
    def _driver(self) -> Optional[neo4j.AsyncDriver]:
        return self._ltm._driver

    @property
    def _database(self) -> str:
        return self._ltm._database

    @property
    def available(self) -> bool:
        return self._ltm._available and self._driver is not None

    # ------------------------------------------------------------------
    # Entity CRUD
    # ------------------------------------------------------------------

    async def upsert_entity(
        self,
        name: str,
        entity_type: str = "concept",
        description: str = "",
        session_id: str = "",
    ) -> Dict[str, Any]:
        """Insert or update an entity.  Deduplicates by semantic name similarity."""
        if not self.available or not name or not name.strip():
            return {"success": False, "message": "Graph not available or empty name"}

        from embeddings import embed_texts, EmbeddingError, EMBEDDINGS_ENABLED

        doc_text = f"{name}: {description}" if description else name
        vector: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                vecs = await embed_texts([doc_text])
                vector = vecs[0] if vecs else None
            except (EmbeddingError, Exception) as exc:
                logger.debug("[KnowledgeGraph] Embedding failed for entity: %s", exc)

        assert self._driver is not None
        now = datetime.now().isoformat()
        name_stripped = name.strip()
        desc_stripped = description.strip()

        async with self._driver.session(database=self._database) as session:
            # Dedup: check if a semantically similar entity already exists
            if vector is not None:
                try:
                    result = await session.run(
                        "CALL db.index.vector.queryNodes("
                        "  'entity_embedding_idx', 1, $vector"
                        ") YIELD node, score "
                        "WHERE score >= $threshold "
                        "RETURN node, score",
                        vector=vector,
                        threshold=_ENTITY_DEDUP_THRESHOLD,
                    )
                    record = await result.single()
                    if record:
                        existing = record["node"]
                        existing_id = existing["id"]
                        mention_count = existing.get("mention_count", 1) + 1
                        sessions = json.loads(existing.get("source_sessions", "[]"))
                        if session_id and session_id not in sessions:
                            sessions.append(session_id)
                        existing_desc = existing.get("description", "")
                        new_doc = (
                            f"{name_stripped}: {desc_stripped}"
                            if desc_stripped
                            else name_stripped
                        )
                        use_doc = (
                            new_doc
                            if len(new_doc) > len(existing_desc)
                            else existing_desc
                        )
                        update_props: Dict[str, Any] = {
                            "mention_count": mention_count,
                            "source_sessions": json.dumps(sessions),
                            "last_seen": now,
                            "description": use_doc,
                        }
                        if vector is not None:
                            update_props["embedding"] = vector

                        await session.run(
                            "MATCH (e:Entity {id: $eid}) " "SET e += $props",
                            eid=existing_id,
                            props=update_props,
                        )
                        return {
                            "success": True,
                            "entity_id": existing_id,
                            "merged": True,
                            "mention_count": mention_count,
                        }
                except Exception as exc:
                    logger.debug("[KnowledgeGraph] Entity dedup check failed: %s", exc)

            # New entity
            entity_id = str(uuid.uuid4())
            props: Dict[str, Any] = {
                "id": entity_id,
                "name": name_stripped,
                "entity_type": entity_type,
                "description": (
                    f"{name_stripped}: {desc_stripped}"
                    if desc_stripped
                    else name_stripped
                ),
                "mention_count": 1,
                "first_seen": now,
                "last_seen": now,
                "source_sessions": json.dumps([session_id] if session_id else []),
            }
            if vector is not None:
                props["embedding"] = vector

            try:
                await session.run(
                    "CREATE (e:Entity) SET e = $props",
                    props=props,
                )
                return {"success": True, "entity_id": entity_id, "merged": False}
            except Exception as exc:
                logger.error("[KnowledgeGraph] Entity store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    # ------------------------------------------------------------------
    # Relationship CRUD
    # ------------------------------------------------------------------

    async def store_relationship(
        self,
        source: str,
        target: str,
        relation: str,
        evidence: str = "",
        confidence: float = 0.8,
        session_id: str = "",
        step_id: int = 0,
    ) -> Dict[str, Any]:
        """Store a directed relationship between two entities."""
        if not self.available:
            return {"success": False, "message": "Graph not available"}
        if not source.strip() or not target.strip() or not relation.strip():
            return {
                "success": False,
                "message": "Source, target, and relation required",
            }

        assert self._driver is not None
        rel_id = str(uuid.uuid4())
        now = datetime.now().isoformat()

        async with self._driver.session(database=self._database) as session:
            try:
                await session.run(
                    "MATCH (s:Entity {name: $source}) "
                    "MATCH (t:Entity {name: $target}) "
                    "CREATE (s)-[:RELATES_TO {"
                    "  id: $rel_id, relation_type: $relation, "
                    "  confidence: $confidence, evidence: $evidence, "
                    "  session_id: $session_id, step_id: $step_id, "
                    "  created_at: $now"
                    "}]->(t)",
                    source=source.strip(),
                    target=target.strip(),
                    rel_id=rel_id,
                    relation=relation.strip(),
                    confidence=confidence,
                    evidence=evidence.strip(),
                    session_id=session_id,
                    step_id=step_id,
                    now=now,
                )
                return {"success": True, "relationship_id": rel_id}
            except Exception as exc:
                logger.error("[KnowledgeGraph] Relationship store failed: %s", exc)
                return {"success": False, "message": str(exc)}

    # ------------------------------------------------------------------
    # Entity search
    # ------------------------------------------------------------------

    async def find_entities(self, query: str, limit: int = 5) -> List[Dict[str, Any]]:
        """Find entities semantically similar to *query*."""
        if not self.available:
            return []

        from embeddings import (
            embed_query as _embed_q,
            EmbeddingError,
            EMBEDDINGS_ENABLED,
        )

        query_vec: Optional[List[float]] = None
        if EMBEDDINGS_ENABLED:
            try:
                query_vec = await _embed_q(query)
            except (EmbeddingError, Exception) as exc:
                logger.debug("[KnowledgeGraph] Entity search embed failed: %s", exc)

        if query_vec is None:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "CALL db.index.vector.queryNodes("
                    "  'entity_embedding_idx', $limit, $vector"
                    ") YIELD node, score "
                    "RETURN node, score",
                    vector=query_vec,
                    limit=limit,
                )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Entity query failed: %s", exc)
                return []

        entities: List[Dict[str, Any]] = []
        for rec in records:
            node = rec["node"]
            entities.append(
                {
                    "id": node.get("id", ""),
                    "name": node.get("name", ""),
                    "entity_type": node.get("entity_type", ""),
                    "description": node.get("description", ""),
                    "mention_count": node.get("mention_count", 1),
                    "similarity": round(rec["score"], 4),
                }
            )
        return entities

    # ------------------------------------------------------------------
    # Relationship traversal
    # ------------------------------------------------------------------

    async def get_relationships(
        self,
        entity_ids: Optional[List[str]] = None,
        entity_names: Optional[List[str]] = None,
        max_hops: int = 1,
    ) -> List[Dict[str, Any]]:
        """
        Get relationships involving the given entities.

        Supports multi-hop traversal: hop 1 returns direct relationships,
        hop 2 adds relationships of the connected entities, etc.

        Either *entity_ids* or *entity_names* (or both) can be provided.
        Names are matched against the ``name`` property of Entity nodes.
        """
        if not self.available:
            return []

        assert self._driver is not None
        # Resolve entity_ids → names
        names: set[str] = set(entity_names or [])
        if entity_ids:
            async with self._driver.session(database=self._database) as session:
                try:
                    result = await session.run(
                        "MATCH (e:Entity) WHERE e.id IN $ids RETURN e.name AS name",
                        ids=entity_ids,
                    )
                    records = await result.data()
                    for rec in records:
                        if rec["name"]:
                            names.add(rec["name"])
                except Exception:
                    pass

        if not names:
            return []

        # Use variable-length Cypher path for multi-hop traversal
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (seed:Entity) WHERE seed.name IN $names "
                    "MATCH path = (seed)-[r:RELATES_TO*1.."
                    + str(max_hops)
                    + "]-(other:Entity) "
                    "UNWIND relationships(path) AS rel "
                    "WITH DISTINCT rel, startNode(rel) AS src, endNode(rel) AS tgt "
                    "RETURN rel, src.name AS source_entity, tgt.name AS target_entity",
                    names=list(names),
                )
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Relationship traversal failed: %s", exc)
                return []

        seen_ids: set[str] = set()
        all_rels: List[Dict[str, Any]] = []
        for rec in records:
            rel = rec["rel"]
            rel_id = rel.get("id", "")
            if rel_id in seen_ids:
                continue
            seen_ids.add(rel_id)
            all_rels.append(
                {
                    "id": rel_id,
                    "source_entity": rec["source_entity"],
                    "target_entity": rec["target_entity"],
                    "relation_type": rel.get("relation_type", ""),
                    "confidence": rel.get("confidence", 0.0),
                    "evidence": rel.get("evidence", ""),
                    "session_id": rel.get("session_id", ""),
                }
            )
        return all_rels

    # ------------------------------------------------------------------
    # Community detection + summaries
    # ------------------------------------------------------------------

    async def get_communities(
        self, entity_ids: Optional[List[str]] = None
    ) -> List[Dict[str, Any]]:
        """Retrieve community summaries relevant to the given entities."""
        if not self.available:
            return []

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                if entity_ids:
                    result = await session.run(
                        "MATCH (e:Entity)-[:MEMBER_OF]->(c:Community) "
                        "WHERE e.id IN $ids "
                        "RETURN DISTINCT c",
                        ids=entity_ids,
                    )
                else:
                    result = await session.run("MATCH (c:Community) RETURN c LIMIT 20")
                records = await result.data()
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community fetch failed: %s", exc)
                return []

        communities: List[Dict[str, Any]] = []
        for rec in records:
            c = rec["c"]
            entity_id_list = json.loads(c.get("entity_ids", "[]"))
            communities.append(
                {
                    "id": c.get("id", ""),
                    "topic": c.get("topic", ""),
                    "summary": c.get("summary", ""),
                    "entity_ids": entity_id_list,
                    "created_at": c.get("created_at", ""),
                }
            )
        return communities

    async def update_communities(
        self,
        summarize_fn: Callable[[str], Coroutine[Any, Any, str]],
        max_communities: int = 10,
    ) -> int:
        """
        Detect entity communities by relationship co-occurrence and generate
        LLM summaries for each cluster.

        Parameters
        ----------
        summarize_fn:
            Async callable that takes a text prompt and returns an LLM-generated
            summary string.  Provided by the orchestrator to avoid coupling the
            graph layer to a specific LLM backend.
        max_communities:
            Maximum number of communities to process per call.  Prevents
            unbounded sequential LLM calls when the graph is large.

        Returns
        -------
        int
            Number of communities created or updated.
        """
        if not self.available:
            return 0

        clusters = await self._detect_clusters()
        if not clusters:
            return 0

        count = 0
        for cluster_entity_ids, cluster_names in clusters[:max_communities]:
            context = await self._build_cluster_context(
                cluster_entity_ids, cluster_names
            )
            if not context:
                continue

            prompt = (
                "Summarize the following cluster of related entities and their "
                "relationships into a concise paragraph. Focus on the key themes, "
                "connections, and implications:\n\n" + context
            )
            try:
                summary = await summarize_fn(prompt)
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community summarization failed: %s", exc)
                continue

            if not summary or not summary.strip():
                continue

            topic = ", ".join(sorted(cluster_names)[:3])

            community_vector: Optional[List[float]] = None
            try:
                from embeddings import (
                    embed_texts,
                    EmbeddingError,
                    EMBEDDINGS_ENABLED as _EE,
                )

                if _EE:
                    vecs = await embed_texts([summary.strip()])
                    community_vector = vecs[0] if vecs else None
            except Exception:
                pass

            await self._store_community(
                cluster_entity_ids, topic, summary.strip(), community_vector
            )
            count += 1

        logger.debug("[KnowledgeGraph] Updated %d communities.", count)
        return count

    async def _detect_clusters(self) -> List[tuple]:
        """
        Simple community detection: group entities that share >= N relationships.

        Returns list of (entity_id_list, entity_name_set) tuples.
        """
        assert self._driver is not None

        # Fetch adjacency from Neo4j in a single query
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (s:Entity)-[:RELATES_TO]-(t:Entity) "
                    "RETURN s.name AS source, t.name AS target"
                )
                records = await result.data()
            except Exception:
                return []

        if not records:
            return []

        # Build adjacency by entity name
        adjacency: Dict[str, set[str]] = defaultdict(set)
        for rec in records:
            src = rec["source"]
            tgt = rec["target"]
            if src and tgt:
                adjacency[src].add(tgt)
                adjacency[tgt].add(src)

        # Simple greedy clustering
        visited: set[str] = set()
        clusters: List[set[str]] = []

        for entity_name in adjacency:
            if entity_name in visited:
                continue
            cluster: set[str] = {entity_name}
            queue = [entity_name]
            while queue:
                current = queue.pop(0)
                for neighbor in adjacency.get(current, set()):
                    if neighbor in cluster:
                        continue
                    shared = len(adjacency.get(neighbor, set()) & cluster)
                    if shared >= _COMMUNITY_MIN_SHARED_RELS or len(cluster) == 1:
                        cluster.add(neighbor)
                        queue.append(neighbor)
            if len(cluster) >= 2:
                visited |= cluster
                clusters.append(cluster)

        # Resolve names → entity_ids
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "MATCH (e:Entity) RETURN e.name AS name, e.id AS id"
                )
                records = await result.data()
            except Exception:
                return []

        name_to_id: Dict[str, str] = {}
        for rec in records:
            if rec["name"]:
                name_to_id[rec["name"]] = rec["id"]

        final: List[tuple] = []
        for cluster_names in clusters:
            ids = [name_to_id[n] for n in cluster_names if n in name_to_id]
            if len(ids) >= 2:
                final.append((ids, cluster_names))

        return final

    async def _build_cluster_context(
        self, entity_ids: List[str], entity_names: set[str]
    ) -> str:
        """Build a text context for community summarization."""
        assert self._driver is not None
        parts: List[str] = []

        async with self._driver.session(database=self._database) as session:
            # Entity descriptions
            try:
                result = await session.run(
                    "MATCH (e:Entity) WHERE e.id IN $ids "
                    "RETURN e.description AS desc",
                    ids=entity_ids,
                )
                records = await result.data()
                for rec in records:
                    if rec["desc"]:
                        parts.append(f"Entity: {rec['desc']}")
            except Exception:
                pass

            # Relationships between cluster members
            try:
                result = await session.run(
                    "MATCH (s:Entity)-[r:RELATES_TO]->(t:Entity) "
                    "WHERE s.name IN $names AND t.name IN $names "
                    "RETURN s.name AS src, r.relation_type AS rel, t.name AS tgt",
                    names=list(entity_names),
                )
                records = await result.data()
                for rec in records:
                    parts.append(
                        f"Relationship: {rec['src']} → {rec['rel']} → {rec['tgt']}"
                    )
            except Exception:
                pass

        return "\n".join(parts)

    async def _store_community(
        self,
        entity_ids: List[str],
        topic: str,
        summary: str,
        vector: Optional[List[float]] = None,
    ) -> None:
        """Store or update a community summary."""
        assert self._driver is not None
        now = datetime.now().isoformat()

        async with self._driver.session(database=self._database) as session:
            # Check if a community with overlapping entities already exists
            try:
                result = await session.run("MATCH (c:Community) RETURN c")
                records = await result.data()
                for rec in records:
                    c = rec["c"]
                    existing_ids = set(json.loads(c.get("entity_ids", "[]")))
                    overlap = len(existing_ids & set(entity_ids))
                    if overlap >= len(entity_ids) * 0.5:
                        # Update existing community
                        props: Dict[str, Any] = {
                            "entity_ids": json.dumps(entity_ids),
                            "topic": topic,
                            "summary": summary,
                            "updated_at": now,
                        }
                        if vector is not None:
                            props["embedding"] = vector
                        await session.run(
                            "MATCH (c:Community {id: $cid}) SET c += $props",
                            cid=c["id"],
                            props=props,
                        )
                        # Rebuild MEMBER_OF edges
                        await session.run(
                            "MATCH (c:Community {id: $cid})<-[r:MEMBER_OF]-() "
                            "DELETE r",
                            cid=c["id"],
                        )
                        await session.run(
                            "MATCH (c:Community {id: $cid}) "
                            "UNWIND $eids AS eid "
                            "MATCH (e:Entity {id: eid}) "
                            "MERGE (e)-[:MEMBER_OF]->(c)",
                            cid=c["id"],
                            eids=entity_ids,
                        )
                        return
            except Exception:
                pass

            # New community
            community_id = str(uuid.uuid4())
            try:
                props = {
                    "id": community_id,
                    "entity_ids": json.dumps(entity_ids),
                    "topic": topic,
                    "summary": summary,
                    "created_at": now,
                }
                if vector is not None:
                    props["embedding"] = vector
                await session.run(
                    "CREATE (c:Community) SET c = $props",
                    props=props,
                )
                # Create MEMBER_OF edges
                await session.run(
                    "MATCH (c:Community {id: $cid}) "
                    "UNWIND $eids AS eid "
                    "MATCH (e:Entity {id: eid}) "
                    "MERGE (e)-[:MEMBER_OF]->(c)",
                    cid=community_id,
                    eids=entity_ids,
                )
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Community store failed: %s", exc)

    # ------------------------------------------------------------------
    # Graph-aware recall (the main query interface)
    # ------------------------------------------------------------------

    async def recall_graph_context(
        self,
        query: str,
        entity_limit: int = 5,
        max_hops: int = 2,
    ) -> str:
        """
        Build a structured text context from the knowledge graph for a query.

        1. Vector-search entities relevant to the query
        2. Traverse 1–2 hops of relationships from those entities
        3. Retrieve community summaries for the entity clusters
        4. Return formatted text: entities, relationships, communities

        Returns an empty string if the graph has no relevant data.
        """
        if not self.available:
            return ""

        # Step 1: find seed entities
        entities = await self.find_entities(query, limit=entity_limit)
        if not entities:
            return ""

        entity_ids = [e["id"] for e in entities]
        entity_names = [e["name"] for e in entities]

        # Step 2: traverse relationships
        relationships = await self.get_relationships(
            entity_names=entity_names, max_hops=max_hops
        )

        # Step 3: get community summaries
        communities = await self.get_communities(entity_ids=entity_ids)

        # Step 4: format
        parts: List[str] = []

        if entities:
            parts.append("KNOWN ENTITIES:")
            for e in entities:
                line = f"  • {e['name']} ({e['entity_type']})"
                if e.get("mention_count", 1) > 1:
                    line += f" — seen {e['mention_count']}x"
                parts.append(line)

        if relationships:
            parts.append("\nKNOWN RELATIONSHIPS:")
            seen_triples: set[str] = set()
            for r in relationships:
                triple = f"{r['source_entity']} → {r['relation_type']} → {r['target_entity']}"
                if triple in seen_triples:
                    continue
                seen_triples.add(triple)
                parts.append(f"  • {triple}")

        if communities:
            parts.append("\nTHEMATIC CLUSTERS:")
            for c in communities:
                parts.append(f"  [{c['topic']}] {c['summary']}")

        return "\n".join(parts) if parts else ""

    # ------------------------------------------------------------------
    # Stats (for testing / monitoring)
    # ------------------------------------------------------------------

    async def stats(self) -> Dict[str, int]:
        """Return counts of entities, relationships, and communities."""
        if not self.available:
            return {"entities": 0, "relationships": 0, "communities": 0}

        assert self._driver is not None
        async with self._driver.session(database=self._database) as session:
            try:
                result = await session.run(
                    "CALL { MATCH (e:Entity) RETURN count(e) AS c } "
                    "WITH c AS entities "
                    "CALL { MATCH ()-[r:RELATES_TO]->() RETURN count(r) AS c } "
                    "WITH entities, c AS relationships "
                    "CALL { MATCH (co:Community) RETURN count(co) AS c } "
                    "RETURN entities, relationships, c AS communities"
                )
                record = await result.single()
                if record:
                    return {
                        "entities": record["entities"],
                        "relationships": record["relationships"],
                        "communities": record["communities"],
                    }
            except Exception as exc:
                logger.debug("[KnowledgeGraph] Stats query failed: %s", exc)

        return {"entities": 0, "relationships": 0, "communities": 0}
